### PR TITLE
Add Custom Function Runtime

### PR DESCRIPTION
**Pull request by jordanfinners**
To enable Azure Functions Custom Handlers deployments via this github action

When running the current deploy-function github action it cannot deploy a custom handler azure function, you get the following error 
```bash
Run Azure/functions-action@v1
##[Initialize]
##[ValidateParameter]
##[ValidateAzureResource]
Using RBAC for authentication, GitHub Action will perform resource validation.
Sucessfully acquired site configs from function app!
Detected function app sku: Consumption
Sucessfully acquired app settings from function app (RBAC)!
Error: Execution Exception (state: ValidateAzureResource) (step: Invocation)
Error:   Failed to convert custom to FunctionRuntimeConstant
Error: Deployment Failed!
```

Custom handlers now has a Custom Runtime (in preview) as mentioned in the docs https://docs.microsoft.com/en-us/azure/azure-functions/functions-custom-handlers#deploying

To support custom handlers via this github action we need to add Custom as a function runtime constant

### CODE REVIEW

**Comment by jordanfinners** [comment]
Hey @AmrutaKawade is this PR okay or do I also need to raise a issue alongside? :)

**Comment by AmrutaKawade** [comment]
> Hey @AmrutaKawade is this PR okay or do I also need to raise a issue alongside? :)

Can you add description? no need of separate issue. I need some context for this change.

**Comment by jordanfinners** [comment]
> > Hey @AmrutaKawade is this PR okay or do I also need to raise a issue alongside? :)
> 
> Can you add description? no need of separate issue. I need some context for this change.

Yeah I've added this now 👍

**Comment by aksm-ms** [comment]
@Hazhzeng @AmrutaKawade Can you please review this PR and take it to production?

**Comment by chriskuech** [comment]
If this is supported, should it be documented with the other runtimes?

**Pull request merged**
