### PR TITLE
Update actions and nodejs to use Node20

### PR DESCRIPTION
**Pull request by longmauriceproj**
Fixes https://github.com/Azure/functions-action/issues/215

All actions will run on Node 20 since Node 16 is deprecated: https://github.blog/changelog/2024-03-07-github-actions-all-actions-will-run-on-node20-instead-of-node16-by-default/

Updating the actions and relevant files following similar changes made for Node 16 updates: https://github.com/Azure/functions-action/pull/158

There is already another PR open for this issue: https://github.com/Azure/functions-action/pull/217. If that PR addresses the issue entirely, then this PR can be closed.

@anirudhgarg and @eamonoreilly I would like to know if there's anything from my side that I can do to fasten this process.

### CODE REVIEW

**Comment by longmauriceproj** [comment]
@microsoft-github-policy-service agree

**Comment by cobriensr** [comment]
Would love for this to be updated so I can get rid of this warning

**Comment by paulschroeder-tomtom** [comment]
@anirudhgarg @eamonoreilly could you please review/merge this?

**Comment by patelchandni** [comment]
Update to Node 20 is part of PR https://github.com/Azure/functions-action/pull/229

**Pull request closed without merging**
