### PR TITLE
Update action.yml - move to node20

### LINKED ISSUE #215: Node16 becoming deprecated, need new version that utilizes Node20
Received a warning that Node16 actions are deprecated and need to update to Node20

For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.

### PR DESCRIPTION
**Pull request by ctolkien**
Fixes #215

### CODE REVIEW

**Comment by mazimcoder** [comment]
this's been for a while, node16 is soon deprecated, when will this PR get merged?

**Comment by longmauriceproj** [comment]
@anirudhgarg @eamonoreilly Any updates?

**Comment by mazimcoder** [comment]
Looping @patelchandni  into this #217

**Comment by jakub-lesniak-ikea** [comment]
@anirudhgarg @eamonoreilly Please accept this PR, people are counting on those actions to be up to date and not just abandoned.

**Comment by patelchandni** [comment]
Acknowledged. Will pick this up this week.

**Comment by JanekBaumgartRelativity** [comment]
@patelchandni Can we expect any actions on this? It's been 3 weeks now till your last message. No rush since everything is still working  - just checking if it wasn't dropped and if we should look for replacement for this action instead. Thanks!

**Comment by patelchandni** [comment]
Update to Node 20 is part of PR https://github.com/Azure/functions-action/pull/229

**Pull request closed without merging**
