### PR TITLE
Support functions using managed identity to access storage account

### PR DESCRIPTION
**Pull request by rlaveycal**
## Description

- Update storage sdk to latest
- add output `package-url`. This is set when doing package deployment and contains the URL to the package (without any SAS token)
- Support functions using MSI to access the storage account:
    - `AzureWebJobsStorage__accountName` is used to access the storage account (RBAC auth)
    - `WEBSITE_RUN_FROM_PACKAGE_BLOB_MI_RESOURCE_ID` is respected regarding whether to generate a SAS token for `WEBSITE_RUN_FROM_PACKAGE`

## Issues

#181

### CODE REVIEW

**Comment by rlaveycal** [comment]
@patelchandni is there anything I need to do to progress this?

**Comment by rlaveycal** [comment]
bump

**Comment by patelchandni** [comment]
@rlaveycal I'll be reviewing and testing it this week. Thanks for creating this PR.

**Comment by patelchandni** [comment]
Merging this branch into patelchandni/msi branch for further end to end testing and run some pipelines before merging to master.

**Pull request merged**
