### PR TITLE
feat: update nodejs to version 16

### LINKED ISSUE #155: Warning in workflow about nodejs version
It seems that GitHub is deprecating nodejs12 which gives warnings when using this action in a workflow:
image

Warning in text: 
```
Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the following actions to use Node.js 16: azure/arm-deploy, azure/functions-action
```

### PR DESCRIPTION
**Pull request by fsschmitt**
Closes #155 

Given that `node12` is no longer being maintained since April 2022 and the fact that GitHub has deprecated it across all GitHub Actions, this action should also be bumped into the latest LTS version: `node16`.

More information can be found here: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/

## Notes to Maintainers

- [ ] Requires update of repo secret `GAE_FA_NODE12_WCON` -> `GAE_FA_NODE16_WCON`
- [ ] Requires update of repo secret `GAE_FA_NODE12_LCON` -> `GAE_FA_NODE16_LCON`
- [ ] Ensure that all tests are passing successfully

Given that nodejs is deprecated, I've taken the assumption that it should be replaced from nodejs 12 to 16, instead of adding a new test suite just for 16.

Let me know if you believe another approach is better.

### CODE REVIEW

**Comment by fsschmitt** [comment]
@microsoft-github-policy-service agree

**Comment by fsschmitt** [comment]
@anirudhgarg and @eamonoreilly first of all, sorry for pinging you directly. But I would like to know if there's anything from my side that I can do to fasten this process.

**Comment by anirudhgarg** [comment]
I have assigned it to the folks who work on this to review

**Comment by fsschmitt** [comment]
Just as FYI, had to upgrade Typescript version to `v4.8.4`([latest](https://www.npmjs.com/package/typescript)) due to this issue: 
* https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53397 

Which was causing build errors such as:

image

**Comment by patelchandni** [comment]
@fsschmitt Thank you for creating this PR. Merging it to a separate branch to run E2E tests that need secrets. I will merge into master from there.

**Pull request merged**
